
# generated by Buildyard, do not edit. Sets FOUND_REQUIRED if all required
# dependencies are found. Used by Buildyard.cmake
set(FIND_REQUIRED_FAILED)
find_package(Boost 1.41.0 COMPONENTS unit_test_framework system thread filesystem program_options thread serialization QUIET)
if(NOT Boost_FOUND AND NOT BOOST_FOUND)
  set(FIND_REQUIRED_FAILED "${FIND_REQUIRED_FAILED} Boost")
endif()
find_package(AIO  QUIET)
if(NOT AIO_FOUND AND NOT AIO_FOUND)
  set(FIND_REQUIRED_FAILED "${FIND_REQUIRED_FAILED} AIO")
endif()
if(FIND_REQUIRED_FAILED)
  set(FOUND_REQUIRED FALSE)
else()
  set(FOUND_REQUIRED TRUE)
endif()